# Generated by Django 4.2.7 on 2023-12-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('opened_from', models.DateTimeField()),
                ('opened_to', models.DateTimeField()),
            ],
            options={
                'ordering': ('-opened_from',),
                'indexes': [models.Index(fields=['name'], name='poll_poll_name_79354b_idx')],
            },
        ),
    ]
